## Project information
site_name: Pandora SmallSat
site_url: https://github.com/pandoramission
site_description: NASA Pandora Satellite
repo_url: https://github.com/pandoramission


## Social Media
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://github.com/pandoramission
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pandoratwitterhandle
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pandoramission/pandorawebsite

nav:
    - Home : index.md
    - About: about.md
    - Target List: targets.md
    - Blog:
      - blogposts/blogpost1.md
    - People : people.md

theme:
  name: "material"
  custom_dir: docs/override/
  icon:
    logo: Pandora_logo_small
  palette:
    scheme: default
    primary: black
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - search
  - autolinks
  - include-markdown
  - table-reader
## Custom theme additions
extra_javascript:
        - 'stylesheets/extra.js'
extra_css:
        - stylesheets/extra.css
